version: '3'
services:
    app:
        build: .
        # 環境変数
        environment:
            - DEBUG=app:*
        tty: true
        ports:
            - '3000:8080'
        volumes:
            - ./src:/app
        working_dir: /app
        command: npm run dev
