'use client'
import Header from '@/components/Header'
import Parallax from '@/components/Parallax'
import { useTranslations } from 'next-intl'


export default function HomePage() {
  const t = useTranslations('HomePage')

  return (
    <>
    <Parallax />
    <Header />
    <main>
      {t('helloWorld')}
    </main>
    

orem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget neque hendrerit, blandit metus quis, facilisis justo. Maecenas vel maximus ex. Suspendisse elementum sed urna quis fringilla. Vivamus at rhoncus est. Donec consequat tellus arcu, ac sodales lorem aliquam ut. Morbi facilisis convallis ultrices. Nulla vehicula mi ut tempor vestibulum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultricies justo eu accumsan tempor. Duis mattis justo ipsum, laoreet congue urna tempor sed. Vivamus facilisis efficitur elit, ac consectetur velit ultricies nec. Aliquam erat volutpat. Praesent a lacus odio. Proin semper, lorem in finibus semper, mauris orci ultricies felis, id facilisis justo justo id nunc.

Ut a magna sed felis dictum tempor at nec metus. Donec elementum nisl blandit, suscipit felis in, mollis ligula. Aliquam erat volutpat. Vivamus quis orci felis. Cras ullamcorper vel enim quis euismod. Sed vulputate auctor enim, vitae dignissim arcu tincidunt eget. Pellentesque laoreet felis a fringilla bibendum. Fusce condimentum molestie vehicula. Quisque accumsan ligula viverra venenatis maximus. Fusce eros nisl, tristique et nisi ornare, suscipit pulvinar nibh. Cras suscipit nulla et lacus ornare consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Fusce non odio ut urna hendrerit auctor. Nunc sed eros faucibus sapien tincidunt pharetra. Nam at hendrerit erat. Donec at pulvinar dolor, nec lacinia lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec sed ipsum quis nulla elementum euismod a in quam. In dolor ante, euismod pharetra auctor consectetur, feugiat et ligula. Pellentesque mollis, est eget mattis auctor, sapien eros pulvinar purus, vitae tincidunt tortor neque et odio. Maecenas elit tellus, vulputate vitae mauris eu, ornare auctor risus. Cras auctor tincidunt risus. Pellentesque suscipit at ante et hendrerit. Praesent suscipit ligula sed ligula egestas finibus.

Pellentesque mollis posuere mi vitae varius. In hac habitasse platea dictumst. Ut aliquam dui dapibus ipsum iaculis gravida. Phasellus rhoncus dui nec vehicula sodales. Vestibulum eget sapien velit. Duis posuere nulla eu augue iaculis posuere. Donec congue eros sit amet lacus tincidunt bibendum. Sed luctus ex vel mi aliquam mollis. Morbi nec interdum odio, ut posuere metus. Proin ultrices nunc quis nisi lobortis bibendum. Phasellus ut pharetra lacus, id semper tellus. Donec libero nunc, laoreet vitae lobortis sed, dignissim at dui. Sed malesuada sapien eu magna volutpat, in elementum mi sagittis. Donec posuere erat vel lectus tincidunt blandit.

Phasellus quis commodo tortor, non tincidunt enim. Nulla quis lacus eros. Aliquam tincidunt consequat bibendum. Proin vitae sapien erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce efficitur eleifend tristique. Vestibulum rutrum molestie vestibulum.

Nullam elementum magna sed nisl egestas semper. Curabitur gravida eu arcu non ullamcorper. Curabitur in pellentesque enim, ac lacinia turpis. Phasellus viverra orci et augue euismod, vel venenatis erat tincidunt. Nam sed mauris nec nulla facilisis suscipit vel quis eros. Praesent pellentesque aliquet nulla, et fringilla massa tincidunt vel. Duis pretium lorem in ultrices aliquet. Fusce quis lacinia eros. In non pellentesque lorem. Vestibulum aliquam neque sollicitudin, euismod nisi id, pulvinar tortor. Vivamus ultrices nisi vel ante eleifend fermentum.

Nam sed neque nunc. Quisque dignissim imperdiet risus et venenatis. Integer sit amet enim ac eros rutrum sagittis eget sit amet nunc. Nam tortor magna, accumsan a ligula in, dapibus vestibulum mauris. Nulla lectus metus, mattis maximus sem in, mollis iaculis tortor. Donec ultrices laoreet elementum. Nam ac turpis sit amet ante vulputate ullamcorper. Pellentesque semper sapien consectetur ipsum dapibus porttitor. Curabitur id urna a urna varius mattis. Donec vitae vestibulum elit.

Aliquam sodales erat lectus, faucibus faucibus nunc ultricies at. Sed vel volutpat nisl, ut maximus quam. Suspendisse vestibulum, massa eu laoreet commodo, metus sem tempus neque, sed rutrum diam nibh non purus. Integer lorem dolor, posuere id quam eu, vestibulum suscipit urna. Fusce vulputate urna pharetra, volutpat leo at, aliquet ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam vitae mollis ipsum. Sed nec ullamcorper erat, id semper massa. Curabitur et pretium tortor, non vulputate odio. Maecenas in lectus fermentum dui bibendum hendrerit vel at libero. Nulla aliquam faucibus accumsan. Phasellus lacinia lacinia tortor, nec euismod felis suscipit sit amet. Sed commodo sit amet felis eget volutpat.

Donec consectetur at eros in laoreet. Suspendisse vitae sagittis est. Ut blandit in leo ut laoreet. Vestibulum ut cursus augue. Integer venenatis odio et tortor eleifend, in venenatis leo mollis. Morbi gravida lacus at arcu eleifend tempor. Aenean id dignissim diam, cursus posuere neque. Etiam massa ligula, malesuada eget imperdiet pretium, viverra a leo. Aliquam at lacus id tortor hendrerit maximus nec et arcu. In non fermentum nibh. Curabitur hendrerit molestie metus ultricies semper. Praesent malesuada quam quis dui rutrum maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean sed vehicula justo, in elementum quam. L
orem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget neque hendrerit, blandit metus quis, facilisis justo. Maecenas vel maximus ex. Suspendisse elementum sed urna quis fringilla. Vivamus at rhoncus est. Donec consequat tellus arcu, ac sodales lorem aliquam ut. Morbi facilisis convallis ultrices. Nulla vehicula mi ut tempor vestibulum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultricies justo eu accumsan tempor. Duis mattis justo ipsum, laoreet congue urna tempor sed. Vivamus facilisis efficitur elit, ac consectetur velit ultricies nec. Aliquam erat volutpat. Praesent a lacus odio. Proin semper, lorem in finibus semper, mauris orci ultricies felis, id facilisis justo justo id nunc.

Ut a magna sed felis dictum tempor at nec metus. Donec elementum nisl blandit, suscipit felis in, mollis ligula. Aliquam erat volutpat. Vivamus quis orci felis. Cras ullamcorper vel enim quis euismod. Sed vulputate auctor enim, vitae dignissim arcu tincidunt eget. Pellentesque laoreet felis a fringilla bibendum. Fusce condimentum molestie vehicula. Quisque accumsan ligula viverra venenatis maximus. Fusce eros nisl, tristique et nisi ornare, suscipit pulvinar nibh. Cras suscipit nulla et lacus ornare consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Fusce non odio ut urna hendrerit auctor. Nunc sed eros faucibus sapien tincidunt pharetra. Nam at hendrerit erat. Donec at pulvinar dolor, nec lacinia lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec sed ipsum quis nulla elementum euismod a in quam. In dolor ante, euismod pharetra auctor consectetur, feugiat et ligula. Pellentesque mollis, est eget mattis auctor, sapien eros pulvinar purus, vitae tincidunt tortor neque et odio. Maecenas elit tellus, vulputate vitae mauris eu, ornare auctor risus. Cras auctor tincidunt risus. Pellentesque suscipit at ante et hendrerit. Praesent suscipit ligula sed ligula egestas finibus.

Pellentesque mollis posuere mi vitae varius. In hac habitasse platea dictumst. Ut aliquam dui dapibus ipsum iaculis gravida. Phasellus rhoncus dui nec vehicula sodales. Vestibulum eget sapien velit. Duis posuere nulla eu augue iaculis posuere. Donec congue eros sit amet lacus tincidunt bibendum. Sed luctus ex vel mi aliquam mollis. Morbi nec interdum odio, ut posuere metus. Proin ultrices nunc quis nisi lobortis bibendum. Phasellus ut pharetra lacus, id semper tellus. Donec libero nunc, laoreet vitae lobortis sed, dignissim at dui. Sed malesuada sapien eu magna volutpat, in elementum mi sagittis. Donec posuere erat vel lectus tincidunt blandit.

Phasellus quis commodo tortor, non tincidunt enim. Nulla quis lacus eros. Aliquam tincidunt consequat bibendum. Proin vitae sapien erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce efficitur eleifend tristique. Vestibulum rutrum molestie vestibulum.

Nullam elementum magna sed nisl egestas semper. Curabitur gravida eu arcu non ullamcorper. Curabitur in pellentesque enim, ac lacinia turpis. Phasellus viverra orci et augue euismod, vel venenatis erat tincidunt. Nam sed mauris nec nulla facilisis suscipit vel quis eros. Praesent pellentesque aliquet nulla, et fringilla massa tincidunt vel. Duis pretium lorem in ultrices aliquet. Fusce quis lacinia eros. In non pellentesque lorem. Vestibulum aliquam neque sollicitudin, euismod nisi id, pulvinar tortor. Vivamus ultrices nisi vel ante eleifend fermentum.

Nam sed neque nunc. Quisque dignissim imperdiet risus et venenatis. Integer sit amet enim ac eros rutrum sagittis eget sit amet nunc. Nam tortor magna, accumsan a ligula in, dapibus vestibulum mauris. Nulla lectus metus, mattis maximus sem in, mollis iaculis tortor. Donec ultrices laoreet elementum. Nam ac turpis sit amet ante vulputate ullamcorper. Pellentesque semper sapien consectetur ipsum dapibus porttitor. Curabitur id urna a urna varius mattis. Donec vitae vestibulum elit.

Aliquam sodales erat lectus, faucibus faucibus nunc ultricies at. Sed vel volutpat nisl, ut maximus quam. Suspendisse vestibulum, massa eu laoreet commodo, metus sem tempus neque, sed rutrum diam nibh non purus. Integer lorem dolor, posuere id quam eu, vestibulum suscipit urna. Fusce vulputate urna pharetra, volutpat leo at, aliquet ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam vitae mollis ipsum. Sed nec ullamcorper erat, id semper massa. Curabitur et pretium tortor, non vulputate odio. Maecenas in lectus fermentum dui bibendum hendrerit vel at libero. Nulla aliquam faucibus accumsan. Phasellus lacinia lacinia tortor, nec euismod felis suscipit sit amet. Sed commodo sit amet felis eget volutpat.

Donec consectetur at eros in laoreet. Suspendisse vitae sagittis est. Ut blandit in leo ut laoreet. Vestibulum ut cursus augue. Integer venenatis odio et tortor eleifend, in venenatis leo mollis. Morbi gravida lacus at arcu eleifend tempor. Aenean id dignissim diam, cursus posuere neque. Etiam massa ligula, malesuada eget imperdiet pretium, viverra a leo. Aliquam at lacus id tortor hendrerit maximus nec et arcu. In non fermentum nibh. Curabitur hendrerit molestie metus ultricies semper. Praesent malesuada quam quis dui rutrum maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean sed vehicula justo, in elementum quam. 
orem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget neque hendrerit, blandit metus quis, facilisis justo. Maecenas vel maximus ex. Suspendisse elementum sed urna quis fringilla. Vivamus at rhoncus est. Donec consequat tellus arcu, ac sodales lorem aliquam ut. Morbi facilisis convallis ultrices. Nulla vehicula mi ut tempor vestibulum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultricies justo eu accumsan tempor. Duis mattis justo ipsum, laoreet congue urna tempor sed. Vivamus facilisis efficitur elit, ac consectetur velit ultricies nec. Aliquam erat volutpat. Praesent a lacus odio. Proin semper, lorem in finibus semper, mauris orci ultricies felis, id facilisis justo justo id nunc.

Ut a magna sed felis dictum tempor at nec metus. Donec elementum nisl blandit, suscipit felis in, mollis ligula. Aliquam erat volutpat. Vivamus quis orci felis. Cras ullamcorper vel enim quis euismod. Sed vulputate auctor enim, vitae dignissim arcu tincidunt eget. Pellentesque laoreet felis a fringilla bibendum. Fusce condimentum molestie vehicula. Quisque accumsan ligula viverra venenatis maximus. Fusce eros nisl, tristique et nisi ornare, suscipit pulvinar nibh. Cras suscipit nulla et lacus ornare consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Fusce non odio ut urna hendrerit auctor. Nunc sed eros faucibus sapien tincidunt pharetra. Nam at hendrerit erat. Donec at pulvinar dolor, nec lacinia lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec sed ipsum quis nulla elementum euismod a in quam. In dolor ante, euismod pharetra auctor consectetur, feugiat et ligula. Pellentesque mollis, est eget mattis auctor, sapien eros pulvinar purus, vitae tincidunt tortor neque et odio. Maecenas elit tellus, vulputate vitae mauris eu, ornare auctor risus. Cras auctor tincidunt risus. Pellentesque suscipit at ante et hendrerit. Praesent suscipit ligula sed ligula egestas finibus.

Pellentesque mollis posuere mi vitae varius. In hac habitasse platea dictumst. Ut aliquam dui dapibus ipsum iaculis gravida. Phasellus rhoncus dui nec vehicula sodales. Vestibulum eget sapien velit. Duis posuere nulla eu augue iaculis posuere. Donec congue eros sit amet lacus tincidunt bibendum. Sed luctus ex vel mi aliquam mollis. Morbi nec interdum odio, ut posuere metus. Proin ultrices nunc quis nisi lobortis bibendum. Phasellus ut pharetra lacus, id semper tellus. Donec libero nunc, laoreet vitae lobortis sed, dignissim at dui. Sed malesuada sapien eu magna volutpat, in elementum mi sagittis. Donec posuere erat vel lectus tincidunt blandit.

Phasellus quis commodo tortor, non tincidunt enim. Nulla quis lacus eros. Aliquam tincidunt consequat bibendum. Proin vitae sapien erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce efficitur eleifend tristique. Vestibulum rutrum molestie vestibulum.

Nullam elementum magna sed nisl egestas semper. Curabitur gravida eu arcu non ullamcorper. Curabitur in pellentesque enim, ac lacinia turpis. Phasellus viverra orci et augue euismod, vel venenatis erat tincidunt. Nam sed mauris nec nulla facilisis suscipit vel quis eros. Praesent pellentesque aliquet nulla, et fringilla massa tincidunt vel. Duis pretium lorem in ultrices aliquet. Fusce quis lacinia eros. In non pellentesque lorem. Vestibulum aliquam neque sollicitudin, euismod nisi id, pulvinar tortor. Vivamus ultrices nisi vel ante eleifend fermentum.

Nam sed neque nunc. Quisque dignissim imperdiet risus et venenatis. Integer sit amet enim ac eros rutrum sagittis eget sit amet nunc. Nam tortor magna, accumsan a ligula in, dapibus vestibulum mauris. Nulla lectus metus, mattis maximus sem in, mollis iaculis tortor. Donec ultrices laoreet elementum. Nam ac turpis sit amet ante vulputate ullamcorper. Pellentesque semper sapien consectetur ipsum dapibus porttitor. Curabitur id urna a urna varius mattis. Donec vitae vestibulum elit.

Aliquam sodales erat lectus, faucibus faucibus nunc ultricies at. Sed vel volutpat nisl, ut maximus quam. Suspendisse vestibulum, massa eu laoreet commodo, metus sem tempus neque, sed rutrum diam nibh non purus. Integer lorem dolor, posuere id quam eu, vestibulum suscipit urna. Fusce vulputate urna pharetra, volutpat leo at, aliquet ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam vitae mollis ipsum. Sed nec ullamcorper erat, id semper massa. Curabitur et pretium tortor, non vulputate odio. Maecenas in lectus fermentum dui bibendum hendrerit vel at libero. Nulla aliquam faucibus accumsan. Phasellus lacinia lacinia tortor, nec euismod felis suscipit sit amet. Sed commodo sit amet felis eget volutpat.

Donec consectetur at eros in laoreet. Suspendisse vitae sagittis est. Ut blandit in leo ut laoreet. Vestibulum ut cursus augue. Integer venenatis odio et tortor eleifend, in venenatis leo mollis. Morbi gravida lacus at arcu eleifend tempor. Aenean id dignissim diam, cursus posuere neque. Etiam massa ligula, malesuada eget imperdiet pretium, viverra a leo. Aliquam at lacus id tortor hendrerit maximus nec et arcu. In non fermentum nibh. Curabitur hendrerit molestie metus ultricies semper. Praesent malesuada quam quis dui rutrum maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean sed vehicula justo, in elementum quam. 
    </>
  )
}